# Uncomment the next line to define a global platform for your project
# platform :ios, ‘8.0’

target 'JLRoutesMVVM_Demo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for JLRoutesMVVM_Demo
  
  # 网络请求
  pod 'AFNetworking', '~> 3.1.0'
  # 网络请求框架
  pod 'YTKNetwork', '~> 2.0.3'
  # 响应函数式框架
  pod 'ReactiveObjC', '~> 3.0.0'
  # 路由组件化解耦
  pod 'JLRoutes', '~> 2.0.5'
  # 自动布局
  pod 'Masonry', '~> 1.0.2'
  # 对象模型
  pod 'JSONModel', '~> 1.2.0'
  # 刷新
  pod 'MJRefresh', '~> 3.0.8'
  # 图片缓存
  pod 'SDWebImage', '~> 3.8.1'
  # 空内容
  pod 'DZNEmptyDataSet', '~> 1.8.1'
  # 扩展集合
  pod 'JKCategories', '~> 1.6’
  # HUD
  pod 'SVProgressHUD'
  pod 'QMUIKit/QMUIComponents/QMUIEmptyView'
end
